.TH SLANG 1 "May 2025" "0.9.3" "User Commands"
.SH NAME
slang \- does cool things
.SH SYNOPSIS
.B slang
[\fIOPTIONS\fR]
.SH DESCRIPTION
\fBslang\fR is a C++ application that demonstrates how to ship man pages.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show help message and exit.
.TP
.B \-v, \-\-version
Show version information.
.SH EXAMPLES
.TP
Run with default options:
.B slang
.SH AUTHOR
Michael Adelmann <madelmann@github.com>
.SH SEE ALSO
.BR bash (1),
.BR grep (1)
