#!/bin/bash

echo "Post installation..."

echo "Setting environment variable..."

ex -sc 'g/^export SLANG_LIBRARY=\/usr\/local\/share\/slang\/Library/d
$a
export SLANG_LIBRARY=/usr/local/share/slang/Library
.
x' ~/.profile

echo "Done."

