#!/bin/bash

echo "Post installation..."

echo "Setting environment variable..."

ex -sc 'g/^export OBJECTIVESCRIPT_LIBRARY=\/usr\/local\/share\/oscript\/Library/d
$a
export OBJECTIVESCRIPT_LIBRARY=/usr/local/share/oscript/Library
.
x' ~/.profile

echo "Done."

