bin/slang                           usr/bin
bin/slang-dbg                       usr/bin
bin/slang-pkg                       usr/bin
bin/webscript                       usr/bin
debian/slang.sh                     etc/profile.d/
scripts/*                           var/lib/slang/scripts/
share/bash_completion/completions/* usr/share/bash-completion/completions/
share/vim/syntax/*                  usr/share/vim/addons/syntax/
